### ISSUE TITLE
无法连接MongoDB

### ISSUE THREAD

**Issue by mafeifan** [MyHerux/code-note#1]
docker-compose up
日志如下：
```
yapi     | log: -------------------------------------swaggerSyncUtils constructor-----------------------------------------------
yapi     | log: 服务已启动，请打开下面链接访问: 
yapi     | http://127.0.0.1:3001/
yapi     | error: MongoNetworkError: failed to connect to server [127.0.0.1:27027] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27027], mongodb Authentication failed
yapi     | log: mongodb load success...
yapi     | (node:14) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'collection' of undefined
yapi     |     at /api/vendors/exts/yapi-plugin-advanced-mock/server.js:24:38
yapi     |     at processTicksAndRejections (internal/process/task_queues.js:86:5)
yapi     | (node:14) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
yapi     | (node:14) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
yapi     | (node:14) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'collection' of undefined
yapi     |     at /api/vendors/exts/yapi-plugin-statistics/server.js:12:38
yapi     |     at processTicksAndRejections (internal/process/task_queues.js:86:5)
yapi     | (node:14) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
yapi     | (node:14) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'collection' of undefined
yapi     |     at /api/vendors/exts/yapi-plugin-wiki/server.js:7:38
yapi     |     at processTicksAndRejections (internal/process/task_queues.js:86:5)
yapi     | (node:14) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)

```

**Comment by MyHerux** [comment]
你看我写的是需要自己先准备一个mongo，然后将自己的mongo的配置替换到启动起来容器里面的配置。你看错误日志，如果你没有修改配置的话，他默认会连接：127.0.0.1:27027
